name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "blazenote-backend.titanium-vertex.sxplab.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "aa511d12-323c-4e49-b39c-9fc2cd2061d4"
migrations_dir = "./migrations"

[ai] 
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "blazenote"
preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true